hkm:
  virtual-host: 192.168.0.106
  redis:
    master: redis://${hkm.virtual-host}:6379
    slaves:
      - redis://${hkm.virtual-host}:6380
    db: 1
  zookeeper:
    address: ${hkm.virtual-host}:2181
    session-timeout: 10000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newlife?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: woshiniba1
  application:
    name: product
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.102:9000/eureka/
  instance:
    prefer-ip-address: true