server:
  port: 9001
 # port: 9011

eureka:
  instance:
    hostname: 192.168.3.28
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.3.28:9000/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#      routes:
#        - id: product_route
#          uri: lb://product
#          predicates:
#            - Path=/product/**
#          filters:
#            - StripPrefix=1
  application:
    name: gateway

logging:
  level:
    org.springframework.cloud.gateway: debug